-- MySQL Script generated by MySQL Workbench
-- Tue May  3 14:11:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jpurcell
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema plantgram
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jpurcell` DEFAULT CHARACTER SET utf8 ;
USE `jpurcell` ;

-- -----------------------------------------------------
-- Table `jpurcell`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jpurcell`.`user` (
  `email` VARCHAR(50) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `profile` VARCHAR(100) NULL,
  `profilePict` VARCHAR(200) NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jpurcell`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jpurcell`.`posts` (
  `idposts` INT NOT NULL,
  `user_email` VARCHAR(50) NOT NULL,
  `caption` VARCHAR(100) NOT NULL,
  `picture` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idposts`),
  INDEX `fk_posts_user_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk_posts_user`
    FOREIGN KEY (`user_email`)
    REFERENCES `jpurcell`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
